export interface TrophyItem {
  id: string;
  category: 'HACKATHON' | 'CERTIFICATION' | 'ALGORITHMIC' | 'OPEN_SOURCE';
  badgeTitle: string;
  rank: string;
  title: string;
  organization: string;
  date: string;
  desc: string;
  proofBadge: string;
  credentialId?: string;
  verificationUrl?: string;
  technologies: string[];
  metrics: { label: string; value: string };
  citation: string;
}

export const TROPHIES: TrophyItem[] = [
  {
    id: 'google-skills-cert',
    category: 'CERTIFICATION',
    badgeTitle: 'OFFICIAL GOOGLE CREDENTIAL',
    rank: 'VERIFIED BADGE',
    title: 'Google Cloud & AI Skills Certification',
    organization: 'Google',
    date: 'Feb 2026',
    desc: 'Official Google Cloud skill badge demonstrating architectural competency across Google Cloud infrastructure, Vertex AI, foundation models, and prompt orchestration.',
    proofBadge: 'VERIFIED GOOGLE BADGE',
    credentialId: '22452714',
    verificationUrl: 'https://www.skills.google/public_profiles/d3cd40a2-7c2b-42a3-bfd6-9e2757010a2b/badges/22452714',
    technologies: ['Google Cloud', 'Vertex AI', 'Prompt Engineering', 'Generative AI'],
    metrics: { label: 'Badge ID', value: '22452714' },
    citation: 'Conferred via Google Skills Boost profile ecosystem for verified cloud & foundation model deployment proficiency.',
  },
  {
    id: 'promptwars-hack2skill',
    category: 'HACKATHON',
    badgeTitle: 'GOOGLE FOR DEVELOPERS',
    rank: 'VERIFIED FINISHER',
    title: 'PromptWars Virtual — Build with AI Challenge 3',
    organization: 'Google for Developers / Hack2Skill',
    date: 'Aug 2026',
    desc: 'Engineered complex prompt pipelines and multi-agent reasoning loops under competitive sprint constraints in the Google for Developers Build with AI arena.',
    proofBadge: 'HACK2SKILL VERIFIED',
    credentialId: '2026H2S06PWVCHL3-A00842',
    verificationUrl: 'https://certificate.hack2skill.com/verify/2026H2S06PWVCHL3-A00842',
    technologies: ['Google Gemini', 'Prompt Engineering', 'Hack2Skill', 'Python'],
    metrics: { label: 'Verification ID', value: 'PWVCHL3-A00842' },
    citation: 'Verified achievement certificate awarded for exceptional prompt architecture in national Hack2Skill arena.',
  },
  {
    id: 'dtv-core-recognition',
    category: 'OPEN_SOURCE',
    badgeTitle: 'EXECUTIVE LEADERSHIP',
    rank: 'CTO & TECH TEAM LEAD',
    title: 'Certificate of Recognition — UI/UX & Tech Team',
    organization: 'Digital Twin Verse (DTV)',
    date: 'Aug 2026',
    desc: 'Honored for exceptional technical leadership as Chief Technology Officer, directing web infrastructure, scalable frontend architectures, and UI/UX design systems.',
    proofBadge: 'OFFICIAL DTV VERIFIED',
    credentialId: 'DTV-CORE-2026-006',
    verificationUrl: 'https://digital-twin-certificates.onrender.com/verify/DTV-CORE-2026-006',
    technologies: ['Full-Stack Architecture', 'UI/UX Design', 'Digital Twins', 'Next.js'],
    metrics: { label: 'Record ID', value: 'DTV-CORE-006' },
    citation: 'Awarded by Digital Twin Verse board for outstanding executive direction and technical product delivery.',
  },
  {
    id: 'kaggle-ai-agents',
    category: 'CERTIFICATION',
    badgeTitle: 'KAGGLE ACCREDITATION',
    rank: 'INTENSIVE SPECIALIST',
    title: '5-Day AI Agents: Intensive Vibe Coding',
    organization: 'Kaggle',
    date: 'Jul 2026',
    desc: 'Rigorous immersion in autonomous AI agents, tool-calling loops, multi-agent collaboration, memory stores, and rapid generative prototyping.',
    proofBadge: 'KAGGLE BADGE VERIFIED',
    credentialId: 'rudrabhullar/108',
    verificationUrl: 'https://www.kaggle.com/certification/badges/rudrabhullar/108',
    technologies: ['Kaggle', 'Autonomous Agents', 'LangChain', 'Python', 'Tool Calling'],
    metrics: { label: 'Kaggle Badge', value: '#108' },
    citation: 'Certified proficiency in building autonomous agentic tool systems and vibe coding workflows.',
  },
  {
    id: 'unstop-build-with-bharat',
    category: 'HACKATHON',
    badgeTitle: 'NATIONAL CHALLENGE',
    rank: 'CERTIFIED PARTICIPANT',
    title: 'Build With Bharat Challenge',
    organization: 'Unstop',
    date: 'Aug 2026',
    desc: 'Designed scalable civic technology prototypes targeting public governance, high-velocity community accessibility, and demographic personalization.',
    proofBadge: 'UNSTOP VERIFIED',
    credentialId: 'f7b684fe-2dbd-421c-a70c-fac466ba2fca',
    verificationUrl: 'https://unstop.com/certificate-preview/f7b684fe-2dbd-421c-a70c-fac466ba2fca',
    technologies: ['Next.js', 'FastAPI', 'Civic Tech', 'Cloud Architecture'],
    metrics: { label: 'Challenge Stage', value: 'National' },
    citation: 'Recognized by Unstop for high-impact innovation addressing real-world Indian demographic challenges.',
  },
  {
    id: 'sih-internal-rgpv',
    category: 'HACKATHON',
    badgeTitle: 'SIH INSTITUTE SELECTION',
    rank: 'COLLEGE FINALIST',
    title: 'Smart India Hackathon (SIH) Internal Hackathon',
    organization: 'UIT RGPV / MoE Innovation Cell',
    date: 'Sep 2025',
    desc: 'Shortlisted among top engineering teams at UIT RGPV to represent the institute for Smart India Hackathon problem statements solving civic bottlenecks.',
    proofBadge: 'INSTITUTE SELECTED',
    credentialId: 'UIT-RGPV-SIH-2025',
    technologies: ['FastAPI', 'Python', 'AI Systems', 'System Design'],
    metrics: { label: 'College Selection', value: 'Shortlisted' },
    citation: 'Selected by university evaluation jury for architectural rigor and systemic feasibility.',
  },
  {
    id: 'agentic-premier-league',
    category: 'HACKATHON',
    badgeTitle: 'GOOGLE FOR DEVELOPERS',
    rank: 'NATIONAL FINALS',
    title: 'Agentic Premier League Finals Certificate of Achievement',
    organization: 'Google for Developers',
    date: 'May 2025',
    desc: 'Competed at national finals in building multi-agent coordination systems, autonomous tool invocation routines, and low-latency agent workflows.',
    proofBadge: 'GOOGLE RECOGNIZED',
    credentialId: 'APL-FINALS-2025',
    technologies: ['Gemini 1.5', 'Agentic Workflows', 'Tool Calling', 'FastAPI'],
    metrics: { label: 'Arena Stage', value: 'Finals' },
    citation: 'Conferred by Google for Developers for high-velocity agentic reasoning and orchestration.',
  },
  {
    id: 'leetcode-algorithmic-rigor',
    category: 'ALGORITHMIC',
    badgeTitle: 'COMPETITIVE RIGOR',
    rank: 'TOP PERCENTILE',
    title: 'Core Data Structures & Algorithmic Problem Solving',
    organization: 'LeetCode & Competitive Coding',
    date: '2024-2026',
    desc: 'Rigorous computational problem solving covering Dynamic Programming, Graph Theory, Segment Trees, Backtracking, and Asymptotic Optimization in Java.',
    proofBadge: 'TOP CODING RIGOR',
    credentialId: 'LC-rudraism19',
    technologies: ['Java', 'Graph Theory', 'Dynamic Programming', 'DSA'],
    metrics: { label: 'Rigor Level', value: 'Advanced' },
    citation: 'Consistent sub-millisecond execution times and mathematically optimal space-time bounds.',
  },
  {
    id: 'technoverse-code-manthan',
    category: 'OPEN_SOURCE',
    badgeTitle: 'CAMPUS LEADERSHIP',
    rank: 'TECH TEAM VOLUNTEER',
    title: 'Code Manthan 2.0 — Tech Team Volunteer',
    organization: 'Technoverse Club, UIT RGPV',
    date: 'Apr 2026',
    desc: 'Organized and coordinated institute-wide coding event promoting algorithmic problem solving, peer mentorship, and competitive programming culture.',
    proofBadge: 'TECHNOVERSE RECOGNIZED',
    credentialId: 'TECHNOVERSE-CM2-2026',
    technologies: ['Campus Mentorship', 'Algorithmic Problem Setting', 'Java / Python'],
    metrics: { label: 'Participants', value: '150+' },
    citation: 'Recognized by Technoverse Club leadership for spearheading technical operations and challenge design.',
  },
];
